name: Java CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: maven
      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ACR_ENDPOINT }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Setup github packages
        uses: s4u/maven-settings-action@v3.0.0
        with:
          servers: |
            [{
                "id": "github",
                "username": "${{ secrets.GH_USER }}",
                "password": "${{ secrets.PAT }}"
            }]
      - name: Build, test and push image
        run: mvn -Ddocker.image.prefix=${{ secrets.ACR_ENDPOINT }} --batch-mode --update-snapshots verify jib:build
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/postgres
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: postgres
          GITHUB_TOKEN_REF: ${{ secrets.PAT }}
          GITHUB_USER_REF: ${{ secrets.GH_USER }}


  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          allow-no-subscriptions: true


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp update -n ${{ secrets.CONTAINER_APP }} -g ${{ secrets.RESOURCE_GROUP }} --image ${{ secrets.ACR_ENDPOINT }}/testlab2-krav:${{ github.sha }} --subscription  ${{ secrets.SUBSCRIPTION_ID }}


