name: Deploy Prod

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          allow-no-subscriptions: true


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp update -n ca-ddt-testlab2-prod-krav -g RG-DDT-Testlab2-prod --image acrddtprod.azurecr.io/testlab2-krav:${{ github.sha }} --subscription 47609472-33dd-49d1-8f78-0ed39b182ff2


